import {
  StyleSheet,
  Dimensions,
} from 'react-native';
const screenWidth = Dimensions.get('window').width;
const styles = StyleSheet.create({
  mainContainer:{
    flex:1,
    justifyContent:'space-between',
    backgroundColor:'#FFFFFF'
  },
  container:{
    backgroundColor:'#FFFFFF',
    flex:1,
  },
  inputRow:{
    height:40,
    width:screenWidth,
    marginBottom:10,
    alignItems:'center',
    //justifyContent:'center',
    flexDirection:'row',
    borderTopWidth:1,
    borderBottomWidth:1,
    borderColor:'#e4e4e4',
    paddingLeft:20,
    paddingRight:20,
  },
  icon:{
    marginRight:10,   
  },
  text:{
    fontSize:14,
  },
  inputLayout:{
    flex:1,
    marginLeft:10,
  },
  label:{
    width:100,
    //alignItems:'center',
    justifyContent:'center',
    marginLeft:28,
  },
  labelText:{
    color:'#515151',
  },
  logo:{
    height:210,
    resizeMode:'cover',
    width:screenWidth,
  },
  logoRow:{
    marginBottom:50,
    height:200,
  },
  submitButton:{
    backgroundColor:'#007cca',
    alignItems:'center',
    justifyContent:'center',
    borderRadius:5,
    height:48,
    width:screenWidth-32,
  },
  buttonRow:{
    flex:1,
    alignItems:'center',
    justifyContent:'center',
    marginBottom:10,
    paddingLeft:16,
    paddingRight:16,
    marginTop:50,
  },
  buttonText:{
    color:'#FFFFFF',
  },
  bottomOtherRow:{
    marginLeft:28,
    marginRight:28,
    justifyContent:'space-between',
    alignItems:'center',
    flexDirection:'row',
    flexWrap:'nowrap',
  },
  footer:{
    flexDirection:'row',
    width:screenWidth-32,
    height:20,
    marginTop:10,
    justifyContent:"space-between",
    alignItems:"center"
  },
  link:{
  },
  footerText:{
    color:'#797979'
  },
  jumpbutton:{
    position:'absolute',
    bottom:0,
    left:0,
    right:0,
    height:50,
    alignItems:'center',
    justifyContent:'center',
    borderTopWidth:1,
    borderTopColor:'#cdcdcd'
  },
  jumpbutton1:{
    backgroundColor:'#FFFFFF',
    height:50,
    alignItems:'center',
    justifyContent:'center',
    borderTopWidth:1,
    borderTopColor:'#cdcdcd'
  }
});
export default styles;